language: android

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      env: ANDROID_HOME=/usr/local/opt/android-sdk
      osx_image: xcode8

before_install:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew update > /dev/null; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew install android-sdk; fi

install:
  - echo y | android update sdk -u -a -t tools
  - echo y | android update sdk -u -a -t platform-tools
  - echo y | android update sdk -u -a -t build-tools-24.0.2
  - echo y | android update sdk -u -a -t android-24
  - echo y | android update sdk -u -a -t extra-google-m2repository
  - echo y | android update sdk -u -a -t extra-android-m2repository

script:
  - ./gradlew clean assembleDebug testDebug jacocoDebugReport coveralls -Dscan --configure-on-demand --daemon --parallel --stacktrace --console=plain -Dorg.gradle.jvmargs="-Dfile.encoding=UTF-8"

sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
